CREATE TYPE currency AS ENUM ('USD', 'RUB', 'EUR');

CREATE TABLE orders
(
    order_uid          uuid PRIMARY KEY NOT NULL,
    track_number       VARCHAR NOT NULL,
    entry              VARCHAR NOT NULL,
    date_created       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locale             VARCHAR,
    internal_signature VARCHAR,
    customer_id        VARCHAR,
    delivery_service   VARCHAR,
    shardkey           VARCHAR,
    sm_id              INT,
    oof_shard          VARCHAR
);

CREATE TABLE deliveries
(
    delivery_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_uid   uuid REFERENCES orders (order_uid) UNIQUE,
    name        VARCHAR,
    phone       VARCHAR,
    zip         VARCHAR,
    city        VARCHAR,
    address     VARCHAR,
    region      VARCHAR,
    email       VARCHAR
);

CREATE TABLE payments
(
    payment_id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    transaction   uuid REFERENCES orders (order_uid) UNIQUE,
    request_id    VARCHAR,
    currency      currency DEFAULT 'USD',
    provider      VARCHAR,
    amount        INT,
    payment_dt    BIGINT,
    bank          VARCHAR,
    delivery_cost INT,
    goods_total   INT,
    custom_fee    INT
);

CREATE TABLE items
(
    item_id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_uid    uuid REFERENCES orders (order_uid),
    chrt_id      BIGINT, 
    track_number VARCHAR NOT NULL,
    price        INT,
    rid          VARCHAR,
    name         VARCHAR,
    sale         INT,
    size         VARCHAR,
    total_price  INT,
    nm_id        BIGINT,
    brand        VARCHAR,
    status       INT
);

